name: CI Tests (action/setup-elixir)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp_version}} / ${{matrix.elixir_version}}] CI Tests [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp_version: 18.3.4.11
            elixir_version: 1.5.3
          - otp_version: 19.3.6.13
            elixir_version: 1.6.6
          - otp_version: 19.3.6.13
            elixir_version: 1.7.4
          - otp_version: 20.3.8.26
            elixir_version: 1.8.2
          - otp_version: 20.3.8.26
            elixir_version: 1.9.4
          - otp_version: 21.3.8.16
            elixir_version: 1.10.4
          - otp_version: 23.0.2
            elixir_version: 1.10.4
    steps:
      - uses: actions/setup-elixir@v1.3
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}
      - uses: actions/checkout@v2.3.1
      - run: mix deps.get --only test
      - run: mix test
      - run: elixir -v
      - run: erl -eval "{ok, Version} = file:read_file(filename:join([code:root_dir(), 'releases', erlang:system_info(otp_release), 'OTP_VERSION'])), io:fwrite(Version), halt()." -noshell
